#!/bin/bash

kubectl delete -f storageclass.yaml
kubectl delete -f deployment.yaml
kubectl delete -f clusterrolebinding.yaml
kubectl delete -f clusterrole.yaml
kubectl delete -f rolebinding.yaml
kubectl delete -f role.yaml
kubectl delete -f serviceaccount.yaml
kubectl delete -f namespace.yaml
